version : '3'
services:
  app:
    image: sha256:ef3bc98b0beee60fa8e49a18c0258107124117c4bee74e6a7d29511e11e72740
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/tasktide
    depends_on:
      - mysql
  mysql:
    image: "mysql:8.3.0"
    environment:
      MYSQL_DATABASE: tasktide
      MYSQL_ROOT_PASSWORD: Stefpark77$
    ports:
      - 3307:3306
