services:
  mysql:
    image: "mysql:8.3.0"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Stefpark77$
      MYSQL_DATABASE: tasktide
    ports:
      - "3307:3306"
    networks:
      - tasktide
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672" #JMS Port
      - "15672:15672" #Management Port - default user:pass = guest:guest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - tasktide
  calendarservices:
    image: sha256:7b8cc1a0a884e541f4de0b6114a7e5885020b139e4cb2a88abd9d637345e14be
    restart: always
    ports:
      - 9001:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tasktide?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Stefpark77$
    networks:
      - tasktide
    depends_on:
      - mysql
  taskservices:
    image: sha256:9cdc630734e8cb80186e26b557e5205db96577b629ea570c158738f6c0c9bf81
    restart: always
    ports:
      - 9002:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tasktide?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Stefpark77$
    networks:
      - tasktide
    depends_on:
      - mysql
  projectservices:
    image: sha256:585f9b1772770ee0fecb1214e8ad3d92d5ffeb0775d84e465a2fa20bf1745bd5
    restart: always
    ports:
      - 9003:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tasktide?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Stefpark77$
    networks:
      - tasktide
    depends_on:
      - mysql
  userservices:
    image: sha256:63eabc9fea7de6cb50bae111f79e7a20c4416bd755d29a00e7fba1120cb9557f
    restart: always
    ports:
      - 9000:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tasktide?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Stefpark77$
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - tasktide
    depends_on:
      - mysql
      - rabbitmq
      - authservices
  authservices:
    image: sha256:d8e1a3d6036f8862d226ed9dd85480b7c8de65c33c52acc1c19314eaf3e27e9a
    restart: always
    ports:
      - 8083:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tasktide?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Stefpark77$
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - tasktide
    depends_on:
      - mysql
      - rabbitmq
networks:
  tasktide:
    driver:
      bridge
