services:
  mysql:
    image: "mysql:8.3.0"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Stefpark77$
      MYSQL_DATABASE: tasktide
    ports:
      - "3307:3306"
    networks:
      - tasktide
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672" #JMS Port
      - "15672:15672" #Management Port - default user:pass = guest:guest
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - tasktide
  calendarservices:
    image: sha256:d80173beca2c267aa6e0620b890c7c9431eab12f5e76d64ea4c2225d8c12e735
    restart: always
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tasktide?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Stefpark77$
    networks:
      - tasktide
    depends_on:
      - mysql
  taskservices:
    image: sha256:d80173beca2c267aa6e0620b890c7c9431eab12f5e76d64ea4c2225d8c12e735
    restart: always
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tasktide?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Stefpark77$
    networks:
      - tasktide
    depends_on:
      - mysql
  projectservices:
    image: sha256:d80173beca2c267aa6e0620b890c7c9431eab12f5e76d64ea4c2225d8c12e735
    restart: always
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tasktide?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Stefpark77$
    networks:
      - tasktide
    depends_on:
      - mysql
  userservices:
    image: sha256:cf0d3e157ec74134cc5e83be7e93f54e2fa243ce703506f49cfb97bbcbddcc9a
    restart: always
    ports:
      - 8082:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tasktide?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Stefpark77$
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - tasktide
    depends_on:
      - mysql
      - rabbitmq
      - authservices
  authservices:
    image: sha256:4327b62fa4f1e23c6cb9dbc45d6ae7c38eea15efbd18dab8d56d1feb86b4f1a8
    restart: always
    ports:
      - 8083:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tasktide?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Stefpark77$
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - tasktide
    depends_on:
      - mysql
      - rabbitmq
networks:
  tasktide:
    driver:
      bridge
