spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/tasktide
    username: root
    password: Stefpark77$
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  servlet:
    context-path: /authServices
  port: 8081

rabbitmq:
  queue:
    name: signup
  exchange:
    name: signup_exchange
  routing:
    key: signup_routing_key

security:
  jwt:
    secret-key: test_secret_key