spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3307/tasktide
    username: root
    password: Stefpark77$
server:
  servlet:
    context-path: /taskServices
  port: 8081

security:
  jwt:
    secret-key: test_secret_key